[tool.poetry]
name = "pythonproject-homework-oop"
version = "0.1.0"
description = ""
authors = ["екатерина ермакова <katka_z_jones@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
